### ISSUE TITLE
The "spawning" flags also delete existing entities

### ISSUE THREAD

**Issue by EssieFir** [Z0rdak/Yet-Another-World-Protector#102]
I'm using the spawning-animal and spawning-monster flags on a 1.19.2 Forge server and they appear to be deleting the mobs that were present before the claim.
These mobs are named using name tags and don't despawn outside of a region.

**Comment by Z0rdak** [comment]
The despawning of entities is intentional. I am aware that this mechanic currently also gets rid of named entities.

As a workaround you can try keeping them outside of the region and put them back in, after the flag is added. This way they should not disappear.

I am looking into a "fix" to not remove named entities to avoid this.

I even try to add this to the next update - no promises.

Best regards

**Comment by EssieFir** [comment]
Instead of specifically named entities, it shouldn't remove any entities with the "persistenceRequired" tag set to true, so that the entities don't *have* to be named. (Named entities, when named with a name tag, automatically have this tag set to true anyway)

Thanks for this mod by the way, it's exactly the mod I needed for a project I'm working on, it's very good!

**Comment by Z0rdak** [comment]
Thanks for pointing this property out for me! That make it much easier and more reliable to implement.

**Comment by Z0rdak** [comment]
Resolved with https://github.com/Z0rdak/Yet-Another-World-Protector/commit/6f5e38480f921b21c89634579c6ac50de2e9cb23.

Will be released with YAWP 0.0.3.0-beta
