### ISSUE TITLE
ETA on 1.20.5/1.20.6 Port

### ISSUE THREAD

**Issue by SethHartman13** [Z0rdak/Yet-Another-World-Protector#112]
When will there be a port to 1.20.5/1.20.6 (Fabric)? Or does the versioning just need to be bumped? Based upon what little knowledge I have about 1.20.6 it seems like a bump is just needed.

**Comment by Z0rdak** [comment]
Hi there, I am currently working on the port for 1.20.6 for fabric and neoforge. #110 

Sadly its more than a simple version bump, since 1.20.5 changed the whole NBT system for items to use components.

If you want updates regarding the port, feel free to join the discord and grab the update role.

And please refrain from creating issues for ETAs for versions or ports.

Rather join the discord and just tag me there - thanks :) 

Best regards
