### ISSUE TITLE
Wrong Encoding for text symbol

### ISSUE THREAD

**Issue by Walrus98** [Z0rdak/Yet-Another-World-Protector#119]
![image](https://github.com/user-attachments/assets/b9d2474f-24e4-4487-938a-e62de55ac95b)

Is it normal?

**Comment by Z0rdak** [comment]
Hey, thanks for the issue.

this is not „normal“. But you are the first to report this issue.

Are you using the resource pack or just the mod itself? 

Which YAWP version are you using?

**Comment by Walrus98** [comment]
> Hey, thanks for the issue.
> 
> this is not „normal“. But you are the first to report this issue.
> 
> Are you using the resource pack or just the mod itself?
> 
> Which YAWP version are you using?

I'm using the latest version of the mod for 1.20.1. No resource pack or something like that. I tried to fix the issues downloading your repository and compile the mod by myself. As expected, I get an error about missing encoding in windows 10, I don't know why

**Comment by Walrus98** [comment]
I'm using the latest version of the mod for 1.20.1. No resource pack or something like that. I tried to fix the issues downloading your repository and compile the mod by myself. As expected, I get an error about missing encoding in windows 10, I don't know why

**Comment by Z0rdak** [comment]
I see.
I had this issue also during development. 
i though I fixed it. Sorry.

its because the code is interpreted with a wrong encoding (some windows specific encoding which does not support these symbols) 
since then I switched back to develop on linux so this should not happen in the future.

IIRC this was a setting in gradle or the project setup. Anyway… I’ll fix this in the next days.

for now you can try to add the resource pack from the discord server add list it to be loaded last to fix this issue.
