### ISSUE TITLE
Cannot disable commands for default users

### ISSUE THREAD

**Issue by JavierMarinGuimera** [Z0rdak/Yet-Another-World-Protector#96]
Am I doing anythign wrong? I want to disable ALL commands from "/yawp" and this is my **yawp-common.toml**
![error yawp](https://github.com/Z0rdak/Yet-Another-World-Protector/assets/36456307/ca83f952-b778-497e-a503-e1fdffdc29a7)
Is there any option like "disable-all-commands" or something like that?

**Comment by Z0rdak** [comment]
Hey,

there is no such option to disable all commands. I might add something like this.

The commands of the mods are not disabled with these options in the way that the players are no longer able to see them in the console. 

Disabling these commands entirely is not as easy as it seems, because they are also based on region membership, which is very dynamic. 

Instead, there is a permission check to use these commands. 

With your options, players should be able to **see** the commands **but** should not be allowed to execute them.

That said, I just noticed that the `/wp marker give` command are not considered with this permission check.

I am looking into adding support for LuckyPerms to make handling YAWP commands easier.

**Comment by JavierMarinGuimera** [comment]
But then how do you prevent simple players from executing commands for example /yawp marker give? I mean, if I don't have OP permisions, I shouldn't be able to execute those commands because I can troll everyone by setting up a region for the entire world, right?

Also, with the config that I posted, simple players shouldn't be able to even see the command "/yawp" when they type the slash and I can see it even with that config.

**Comment by JavierMarinGuimera** [comment]
Btw, thank you for your answer!

**Comment by Z0rdak** [comment]
I think I have not expressed myself clearly enough. I'll try it again.

> Also, with the config that I posted, simple players shouldn't be able to even see the command "/yawp" when they type the slash and I can see it even with that config.

That's not true (I am using a custom permission system, because the default vanilla one does not quite fit my needs).

The config **does not** prevent _simple_ players from seeing the commands. 
It **does** prevent _simple_ players from executing the commands, though.

Have you tried to execute the commands with this config setup as a _simple_ player?
You should get a message which tells you that you don't have the needed permission.

> But then how do you prevent simple players from executing commands for example /yawp marker give?

This specific command (`/yawp marker give`) is not yet covered – I simply forgot it. I'll add this in the next patch, so players can't use this command. 
But even with the RegionMarker _simple_ players _should_ not be able to create regions with your config setup – try it out.

**Comment by JavierMarinGuimera** [comment]
I already tried to create a region without any permissions and it let me create it. Let me check again, but I'm 99% sure that I had no OP privileges or something similar.

I'll tell you in a couple of minutes.

**Comment by JavierMarinGuimera** [comment]
Wait, the command is not showing to me right now xd

I love this thing. The moment I notify about a problem is the moment when the problem is solved (apparently) xddddddddd

![imagen](https://github.com/Z0rdak/Yet-Another-World-Protector/assets/36456307/281e36be-ef78-44ce-b50a-b4018d56a4be)

**Comment by JavierMarinGuimera** [comment]
By the way, I have done this on LuckPerms and appears to work correctly (it's writen in Spanish, just in case):
![imagen](https://github.com/Z0rdak/Yet-Another-World-Protector/assets/36456307/4d05a20b-7d23-4dba-a7c3-97bb6418bf9b)

**Comment by JavierMarinGuimera** [comment]
Nevermind. I don't know what happened but the command appears again. I had to restart the server and had to make some changes on a voice chat file.
![imagen](https://github.com/Z0rdak/Yet-Another-World-Protector/assets/36456307/068f498e-4990-4b35-9610-1eb553153d80)

But yes, you are true, people cannot create zones: 
![imagen](https://github.com/Z0rdak/Yet-Another-World-Protector/assets/36456307/6c4a7f35-477a-479a-83d9-928f1355d393)

**Comment by Z0rdak** [comment]
Thanks for the heads-up.

I'll think about a config option to disable specific commands entirely, except for OPs and the server console.

**Comment by EnderMelody** [comment]
still having this problem on version 0.0.2.9-beta3 on fabric 1.20.4. really like the mod but this problem makes it unusable.

**Comment by Z0rdak** [comment]
There are no changes in this version. Its just a port fort 1.20.4. 

The next (WIP) update already has some features that should cover this until the LuckPerms integration is done.

**Comment by EnderMelody** [comment]
ah my bad i assumed there was an update since then. looking forward to the fix as this mod is very promising. and thanks for the quick response.

**Comment by Z0rdak** [comment]
Resolved by https://github.com/Z0rdak/Yet-Another-World-Protector/commit/8b350a12a581365ec5781b82878286bd1146840e and the dedicated checks for the marker command.

Will be released with YAWP 0.0.3.0-beta
