### ISSUE TITLE
Can only place blocks inside claimed region if player right clicks exactly in parameters of cuboid.

### ISSUE THREAD

**Issue by BuufPackJackBoy** [Z0rdak/Yet-Another-World-Protector#97]
You can see in the demonstration when the player places the block against the wall (which is not apart of the claim) it prevents the player however the same location where the block is placed is allowed when right clicking a different block.
![Untitled](https://github.com/Z0rdak/Yet-Another-World-Protector/assets/147353447/3028412f-e68b-42bd-a799-2e84d7cca357)

**Comment by Z0rdak** [comment]
Hey there.

Thanks for creating an issue and providing a gif with it. 

It would be very helpful if you could also provide the following information:

- [x] Minecraft Version: 1.20.1
- [x] Modloader & Version: Fabric 0.14.22
- [x] YAWP Version: 0.0.2.9-beta3

Beside that I'll need to set up some test scenarios myself because I can not infer the region information and block positions from the gif.

Best regards
Z0rdak

**Comment by BuufPackJackBoy** [comment]
I'm using fabric 0.14.22 with YAWP beta 3.0. Thank you for the work you've done with this mod I love it so far.

**Comment by Z0rdak** [comment]
see #94

**Comment by Z0rdak** [comment]
Seems to only affect fabric version. More investigation is needed.

**Comment by Z0rdak** [comment]
I found the issue for this bug.
It will be solved in the next fabric patch (sometime next week).
